language: csharp
install:
  - wget https://raw.githubusercontent.com/hmlendea/deployment-scripts/master/monogame/install-monogame-3.6.sh -O monogame-install.sh
  - bash monogame-install.sh
  - dotnet test NuciXNA.UnitTests
script:
  - dotnet build
