language: csharp
mono: none
dotnet: 2.2
dist: xenial

install:
  - wget https://raw.githubusercontent.com/hmlendea/deployment-scripts/master/monogame/install-monogame.sh
  - bash install-monogame.sh 3.7.1
  - dotnet test NuciXNA.UnitTests
script:
  - dotnet build
